services:
  logistics-db:
    image: postgis/postgis:15-3.3
    container_name: logistics-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logistics
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  logistics-cache:
    image: redis:7.2.6-alpine
    container_name: logistics-cache
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass yourpassword
    volumes:
        - cache-data:/data
  telemetry-mw-rabbitmq:
    image: rabbitmq:3.9.14-management-alpine
    container_name: telemetry-mw-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  cache-data:
    driver: local
  db-data:
    driver: local
